Add nonces to VDAF sharding syntax & Prio3
cfrg/draft-irtf-cfrg-vdaf pull request #117
Opened 2022-09-14 21:02 UTC by hannahdaviscrypto

I came across a concern about the robustness of Prio3.The construction uses a PRG to derive joint randomness from the input shares that is used by the client and all aggregators. If a client uploads the same set of input shares twice under distinct nonces, the aggregators will derive the same joint randomness in both preparation phases.Intuitively, this violates the expectation that the joint randomness is pseudorandom, or at least not completely controllable by an attacker. 
More formally, there is a degenerate FLP that is sound  with L bits of security when each set of input shares is submitted at most once, but is vulnerable to an 2^(L/2)-query attack if they can be submitted under many nonces. 

This PR mitigates the attack by including the nonce in the joint randomness derivation so that if input shares are submitted under two different nonces, they will go through preparation with independent joint randomness. It requires changing VDAF syntax so that Shard takes the nonce as input. There shouldn't be any change to communication as a result, and the operational cost to Prio3 is at worst 1 additional AES call per party.

2022-09-14 22:31 UTC, cjpatton requested changes
Thanks Hannah! This PR will need a couple more things before it can be merged:
1. The definition of Poplar1 needs to be updated to pass `nonce` to `measurement_to_input_shares()`. It's fine that it ignores it, but we want to keep the API boundaries consistent nonetheless.
2. The reference implementation needs to be updated to match. (See the `poc/` folder.) When making a change like this, typically the first step is to update the reference implementation, make sure the tests pass, then copy the updated definitions into the draft.

2022-09-14 22:31 UTC, cjpatton commented on draft-irtf-cfrg-vdaf.md
> +  accommodates the above change to Prio3.
You can remove the change log update; we typically wait to do this until the next draft is cut.

FWIW, I would summarize the Prio3 as follows

> Prio3: Add the nonce to the transcript for joint randomness computation. This improves the provable security bound for robustness.

2022-09-14 22:31 UTC, cjpatton commented on draft-irtf-cfrg-vdaf.md
> +nonce provided by the environment (`nonce`, see {{run-vdaf}}).
I don't think this is all that useful here. 
```suggestion
```

2022-09-15 19:40 UTC, cjpatton requested changes

2022-09-15 19:40 UTC, cjpatton commented on poc/common.sage
> +TEST_VECTOR = True
Let's revert this, as `TEST_VECTOR == True` is only needed for generating test vectors.

2022-09-15 19:40 UTC, cjpatton commented on poc/common.sage
> +DRAFT = '04'
Let's revert this. Bumping the version is usually a chore saved until just before cutting the draft.

2022-09-15 19:40 UTC, cjpatton commented on poc/test_vec/04/Poplar1Aes128_0.json
> +{
There might be other breaking changes for VDAF-04, so we'll wait to update the test vectors until just before cutting.

2022-09-15 19:40 UTC, cjpatton commented on poc/vdaf.sage
>                                                                    Vec[Bytes]):
The spacing here is a bit odd. 
```suggestion
                                    nonce: Bytes) -> (Bytes, Vec[Bytes]):
```

2022-09-15 19:40 UTC, cjpatton commented on poc/vdaf_poplar1.sage
> +    def measurement_to_input_shares(Poplar1, measurement, nonce):
nit: In Python (i.e., Sage :D) it's conventional to prefix ignored parameters with an underscore.
```suggestion
    def measurement_to_input_shares(Poplar1, measurement, _nonce):
```

2022-09-15 19:40 UTC, cjpatton commented on draft-irtf-cfrg-vdaf.md
> +(cf. {{sec-daf-shard}}); in VDAFs it additionally takes a nonce as input and
```suggestion
(cf. {{sec-daf-shard}}); in addition, it takes a nonce as input and 
```

2022-09-15 19:40 UTC, cjpatton commented on draft-irtf-cfrg-vdaf.md
> +def measurement_to_input_shares(Poplar1, measurement, nonce):
```suggestion
def measurement_to_input_shares(Poplar1, measurement, _nonce):
```

2022-09-15 19:40 UTC, cjpatton commented on poc/common.sage
> +TEST_VECTOR = True
Let's revert this. We only want to set `TEST_VECTOR == True` when we want to generate the test vectors; otherwise, the tests use truly random bits, which is what we want.

2022-09-15 19:40 UTC, cjpatton commented on draft-irtf-cfrg-vdaf.md
> +  Client. It consumes the measurement and the nonce and
* `make` fails if a line ends with trailing white space:
  ```
  $ make
  757:Sharding transforms a measurement into input shares as it does in DAFs
  758:(cf. {{sec-daf-shard}}); in VDAFs it additionally takes a nonce as input and
  761:* `Vdaf.measurement_to_input_shares(measurement: Measurement, nonce: Bytes) ->
  763:  Client. It consumes the measurement and the nonce and
  draft-irtf-cfrg-vdaf.md contains trailing whitespace
  *** Run 'make fix-lint' to automatically fix some errors
  make: *** [lint-whitespace] Error 1
  ```

* Also, lines should break at 80 characters.

```suggestion
  Client. It consumes the measurement and the nonce and
```

2022-09-15 20:27 UTC, hannahdaviscrypto commented on poc/common.sage
> +TEST_VECTOR = True
Done

2022-09-15 20:38 UTC, cjpatton commented
Looking good! However, CI is still complaining about spurious whitespace: https://github.com/cfrg/draft-irtf-cfrg-vdaf/actions/runs/3063497529/jobs/4945718835

2022-09-20 19:38 UTC, cjpatton commented
Looking good! One minor nit, then we'll need to "squash" the commits on this branch into a single one. This can be done with an "interactive rebase":

```
$ git rebase main -i
```

This will pull up your editor and give you instructions for how to carry out the rebase. You will "pick" the first commit, then "squash" each subsequent commit into the first. You will have a chance to edit the commit title and message: Make sure the title is succinct (the title of this PR works perfectly fine) and that the message is complete. By "complete" I mean that it should be evident to the reader what has changed and why.

Also, this PR includes an orthogonal change to poc/README.md that fixes some typos. It's great to pick up these kinds of changes in PRs. However, it's important that the commit history reflects all changes, even minimal ones. There are two ways we can address this:
1. (ideal) Pull the change out into a separate commit
2. (perfectly fine, especially for a spec) Note in the commit message that the commit also includes minor editorial changes.

Finally, once the rebase is complete, you will have to "force-push" your branch. Be careful because this rewrites history. (git provides a backup if needed.)

```
$ git push -f
```

2022-09-30 20:49 UTC, cjpatton approved these changes
Nice work!

2022-09-30 21:17 UTC, merged