poc: Generate test vectors for IdpfPoplar
cfrg/draft-irtf-cfrg-vdaf pull request #132
Opened 2023-01-10 23:54 UTC by cjpatton

For a given input `alpha`, generate the expected public and key shares.

2023-01-10 23:56 UTC, cjpatton commented
cc/ @divergentdave this might help you get going. Note that the public share looks highly non-random because the IPDF key shares are identical:
```
{
    "beta_inner": [
        [
            1,
            1
        ],
        [
            1,
            1
        ],
        [
            1,
            1
        ],
        [
            1,
            1
        ],
        [
            1,
            1
        ],
        [
            1,
            1
        ],
        [
            1,
            1
        ],
        [
            1,
            1
        ],
        [
            1,
            1
        ]
    ],
    "beta_leaf": [
        1,
        1
    ],
    "keys": [
        "01010101010101010101010101010101",
        "01010101010101010101010101010101"
    ],
    "public_share": "055555000000000000000000000000000000000000000000000001000000000000000100000000000000000000000000000000ffffffff00000000ffffffff0000000000000000000000000000000000000000ffffffff00000000ffffffff0000000000000000000000000000000000000000ffffffff00000000ffffffff0000000000000000000000000000000000000000ffffffff00000000ffffffff000000000000000000000000000000000000000000000000000000010000000000000001000000000000000000000000000000000000000000000001000000000000000100000000000000000000000000000000000000000000000100000000000000010000000000000000000000000000000000000000000000010000000000000001000000000000000000000000000000007fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffec7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffec"
}
```

2023-01-13 21:08 UTC, divergentdave commented on poc/idpf.sage
> +    printable_beta_leaf = [ elem.as_unsigned() for elem in beta_leaf ]
These should be stringified to avoid JSON library compatibility issues

2023-01-13 21:38 UTC, divergentdave commented on poc/idpf.sage
> +    }
The test vector should include alpha as well, so that it's self-contained. (Perhaps as an array of `0` and `1`?)

2023-01-13 21:52 UTC, cjpatton commented on poc/idpf.sage
> +    }
Are you alright with an unsinged integer here? From the spec perspective, this is the most natural way to represent `alpha`.

2023-01-13 21:59 UTC, divergentdave commented on poc/idpf.sage
> +    }
If we included `bits` as a number and `alpha` as a number-as-a-string, that would work.

2023-01-13 22:14 UTC, cjpatton commented on poc/idpf.sage
> +    printable_beta_leaf = [ elem.as_unsigned() for elem in beta_leaf ]
Done.

2023-01-13 22:15 UTC, cjpatton commented on poc/idpf.sage
> +    }
Done.

2023-01-17 14:41 UTC, divergentdave requested changes

2023-01-17 14:41 UTC, divergentdave commented on poc/idpf.sage
> +        'beta_inner': printable_beta_inner,
```suggestion
        'bits': int(Idpf.BITS),
        'alpha': str(alpha),
        'beta_inner': printable_beta_inner,
```

2023-01-17 14:41 UTC, divergentdave commented on poc/idpf.sage
> +        DRAFT, Idpf.__name__, test_vec_instance), 'w') as f:
We can punt on this for now, but we'll soon need to include the PRG name here.

2023-01-17 22:18 UTC, cjpatton commented on poc/idpf.sage
> +        DRAFT, Idpf.__name__, test_vec_instance), 'w') as f:
Done.

2023-01-17 22:27 UTC, cjpatton commented
@divergentdave just a heads up that I update the value of `alpha` used for unit tests so that bit order is easier to test.

2023-01-17 22:40 UTC, divergentdave approved these changes

2023-01-17 22:53 UTC, cjpatton commented
- [ ] To make this more useful, the key shares should be distinct strings so that the correction words don't end up canceling out.

2023-02-28 15:40 UTC, cjpatton commented
Closed in favor of #162.

2023-02-28 15:40 UTC, closed without merging