Add IDPF test vector
cfrg/draft-irtf-cfrg-vdaf pull request #162
Opened 2023-02-23 23:18 UTC by divergentdave

This is a refresh of #132, rebased on top of #160. I changed it to conditionally override one of the IDPF keys to be `b"\x02" * length`, so that we get a more interesting public share, without runs of zeros. I also checked in the resulting test vector. This has knock-on effects on the Poplar1 test vector, naturally.

2023-02-23 23:33 UTC, cjpatton requested changes
This seems mostly reasonable. My only concern is that the exception in the test vector generation code contradicts this statement in the spec:

> To make the tests deterministic, `gen_rand()` was replaced with a function that returns the requested number of octets.

We need to figure out a way to spell out how the random values are picked.

It may not be strictly necessary to fix this for 04, but it would certainly be nice to have by 05.

2023-02-23 23:33 UTC, cjpatton commented on poc/idpf_poplar.sage
> +        if TEST_VECTOR:
To remind us to delete these lines before copy-pasting into the spec.
```suggestion
        # REMOVE ME
        if TEST_VECTOR:
```

2023-02-28 16:05 UTC, divergentdave commented
Hmm, I suppose if we want to specify which random bytes go where, then making it an explicit input is the simplest way to do so. Sounds good to me.

2023-03-01 00:40 UTC, cjpatton commented
Oops, actually we will want to re-open this once I've addressed #173.

2023-03-01 20:06 UTC, closed without merging