Run Sage tests in CI
cfrg/draft-irtf-cfrg-vdaf pull request #208
Opened 2023-03-21 22:30 UTC by divergentdave

This installs Sage and runs the test suite. See discussion on #204.

2023-03-21 22:38 UTC, divergentdave commented
This is repeatably failing with a 404 when fetching one package, but I can't reproduce the 404 locally. I may try again tomorrow in case this is a package caching issue.

(I didn't go with Docker initially because `sagemath/sagemath:9.6` doesn't include GNU make in its image)

2023-03-22 16:53 UTC, cjpatton commented
Take a look at what @dconnolly set up for FROST: https://github.com/cfrg/draft-irtf-cfrg-frost/blob/master/.github/workflows/poc.yml

2023-03-22 17:47 UTC, cjpatton requested changes

2023-03-22 18:00 UTC, cjpatton approved these changes

2023-03-22 21:54 UTC, merged