Add poc changes for [#177]
cfrg/draft-irtf-cfrg-vdaf pull request #298
Opened 2023-10-03 23:02 UTC by albertpl

Add poc changes for [#177](https://github.com/cfrg/draft-irtf-cfrg-vdaf/issues/177)

2023-10-03 23:21 UTC, albertpl commented on poc/flp_generic.py
> +    def with_field(SumVec, field: field.FftField):
I choose to this approach, instead of making `field` a `__init__` parameter  because
1. Follow existing patterns in `vdaf_prio3.py` where we using `Prio3` as a template to create `Prio3SumVec` etc.
2. `SumVec.Field` is closer to template/generic parameters than instance properties, IMHO

2023-10-03 23:21 UTC, albertpl commented on poc/vdaf_prio3.py
> +    def is_recommended(valid_cls,
We might need to take other parameters from the underlying FLP circuits/gadgets into considerations? e.g. `Valid.GADGET_CALLS`, `GADGET.DEGREE`? What constrains shall we specify ?

2023-10-03 23:21 UTC, albertpl commented on poc/vdaf_prio3.py
> +    def algorithm_id_from(num_proofs: Unsigned,
What algorithm IDs shall we allocate for this variants? 

Let $N$ be the next available algorithm ID. Maybe we can start with $N$ be Field64 with `PROOFS=2` and $N+1$ be Field64 with `PROOFS=3`? Then allocate more algorithm IDs whenever there is request?

2023-10-05 00:12 UTC, cjpatton requested changes
Looking good so far! Very clean for the most part. One high level ask: Please add more context to the commit message. A reference to the issue is somewhat useful, but it's helpful to have a summary of the change in the `git log` as well. (We rely on this heavily when preparing drafts.)

2023-10-05 00:12 UTC, cjpatton commented on poc/vdaf_prio3.py
>              verify_key,
^ s/query_rand/query_rands/ for consistency with joint_rands

2023-10-05 00:12 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        verifier_share = []
Hmm, this is a bit odd; elsewhere we have "proof shares" and "query rands", but here we have just one "verifier share". WDYTA changing this to "verifier shares"? One downside is that, during prep_shares_to_prep we combine the "verifier shares" into the "verifier", so we'd need to change this to "list of verifier shares" into the "verifiers".

Let me know if I'm not making sense :)

2023-10-05 00:12 UTC, cjpatton commented on poc/vdaf_prio3.py
> +class Prio3SumVecWithMultiproof(Prio3SumVec):
We want to make it clear that this is not (yet) on the standards track. We could prefix the class name with `Test`, or maybe just add a comment clarifying what this is intended for.

2023-10-05 00:12 UTC, cjpatton commented on poc/vdaf_prio3.py
> +    ID = 0xFFFFFFFF  # To be set by `with_params`
Why not just set it here? If this behavior is needed, then don't set the ID here.

2023-10-05 00:12 UTC, cjpatton commented on poc/vdaf_prio3.py
> +    def algorithm_id_from(num_proofs: Unsigned,
yeah, for different choices of `PROOFS`, we'd need to distinct code points (i.e., algorithm IDs)

2023-10-05 00:12 UTC, cjpatton commented on poc/vdaf_prio3.py
> +    def joint_rands(Prio3, k_joint_rand_seed):
As @divergentdave suggested, let's incorporate `Prio3.PROOFS` into the transcript for deriving the joint rands.

2023-10-05 16:46 UTC, junyechen1996 commented on poc/vdaf_prio3.py
> +    def joint_rands(Prio3, k_joint_rand_seed):
If Prio3’s derivation of domain separation tag already includes algorithm ID, is it sufficient to make algorithm ID specify a distinct combination of `(Field, PROOFS)`, per thread [here](https://github.com/cfrg/draft-irtf-cfrg-vdaf/pull/298#discussion_r1344864217)?

2023-10-05 16:58 UTC, albertpl commented on poc/common.py
> +ERR_PARAMS_NOT_RECOMMENEDED = Error('parameters are not recommended')
Sounds good. I will create a new class `ParamsNotRecommendedError` inherited from `Exception`.

2023-10-05 17:10 UTC, cjpatton commented on poc/vdaf_prio3.py
> +    def joint_rands(Prio3, k_joint_rand_seed):
That's one possibility, but it somewhat depends on how "configurable" we need the value of `PROOFS` to be. Ideally we can fix it for a given choice of circuit and field.

2023-10-05 17:11 UTC, cjpatton commented on poc/vdaf_prio3.py
> +    def joint_rands(Prio3, k_joint_rand_seed):
I think for now it makes sense to include it in the transcript.

2023-10-05 17:12 UTC, cjpatton commented on poc/common.py
> +ERR_PARAMS_NOT_RECOMMENEDED = Error('parameters are not recommended')
Actually I would follow what we do else where and just `raise ValueError('something bad happened')` like we do elsewhere.

2023-10-05 17:14 UTC, albertpl commented on poc/vdaf_prio3.py
> +        verifier_share = []
sorry to confuse. I want to convey *a share* of multiple verifier message.
I guess we can use `verifiers_share`, i.e. append **s** to verifier, instead of share, what do you think?

2023-10-05 17:16 UTC, albertpl commented on poc/vdaf_prio3.py
> +class Prio3SumVecWithMultiproof(Prio3SumVec):
OK. I will add a comment.

2023-10-05 18:21 UTC, albertpl commented on poc/vdaf_prio3.py
> +        verifier_share = []
Along the same line, (notice **s** appended to `proof`)
`leader_proof_share` -> `leader_proofs_share`
`helper_proof_share` -> `helper_proofs_share`

2023-10-05 19:07 UTC, albertpl commented
[Note, I will squash & summarize all changes in the commit, before merging this PR]

2023-10-05 19:23 UTC, albertpl commented on poc/vdaf_prio3.py
> +    def joint_rands(Prio3, k_joint_rand_seed):
>I think for now it makes sense to include it in the transcript.

Just to clarify. And do we want to use binder string?

2023-10-05 23:34 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        verifier_share = []
Yeah I like that idea. It's grammatically a little hairy but it makes the variable names consistent.

2023-10-05 23:38 UTC, cjpatton commented on poc/vdaf_prio3.py
> +    def joint_rands(Prio3, k_joint_rand_seed):
Yup, at the step where we derive the joint rands from the `k_joint_rand_seed`.

2023-10-06 18:23 UTC, albertpl commented on poc/vdaf_prio3.py
> +        binder = b'' if Prio3.PROOFS == 1 else byte(Prio3.PROOFS)
Choose to be backward compatible, i.e. only embedding `Prio3.PROOFS` when it is > 1.

2023-10-09 16:13 UTC, albertpl commented on poc/vdaf_prio3.py
> +    def joint_rands(Prio3, k_joint_rand_seed):
If we treat (`PROOFS, Field`) as parameter for the underlying algorithm, i.e. same as `SHARES`, it makes senses to add them into joint randomness derivation. 
1. If we do so, maybe we can allocate one algorithm ID/code point for Prio3SumVec variant with multiproofs? 
2. Shall we add field choice into joint randomness derivation too (binder) ?

2023-10-10 19:14 UTC, cjpatton commented on poc/vdaf_prio3.py
> +    def joint_rands(Prio3, k_joint_rand_seed):
> If we treat (`PROOFS, Field`) as parameter for the underlying algorithm, i.e. same as `SHARES`, it makes senses to add them into joint randomness derivation.
> 
>     1. If we do so, maybe we can allocate one algorithm ID/code point for Prio3SumVec variant with multiproofs?

I don't think we should actually allocate a codepoint until we know more about robustness. In the meantime, one is free to use any of the unreserved codepoints however they wish.


>     2. Shall we add field choice into joint randomness derivation too (binder) ?

We maybe don't need to unless we plan to use more than one field. Isn't `Field64` the only one that's needed?

2023-10-10 19:14 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        binder = b'' if Prio3.PROOFS == 1 else byte(Prio3.PROOFS)
Yup, good idea.

2023-10-10 19:44 UTC, cjpatton reviewed
Looking very good! High level ask: Make sure that variable naming conventions are consistent across sharding and preparation.

2023-10-10 19:44 UTC, cjpatton commented on poc/flp_generic.py
> +    for _field in [field.Field64, field.Field96, field.Field128]:
Style question: Why prepend the underscore (`_`)? Is this because `field` is already defined? Is this following a specific Python convention?

I write a lot of rust these days, so I think of this convention as a way of differentiating multiple variables that I want to be anonymous.

2023-10-10 19:44 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        verifier_share = []
For consistency with `shard()`
```suggestion
        verifiers_share = []
```

2023-10-10 19:44 UTC, cjpatton commented on poc/vdaf_prio3.py
>          for (verifier_share, k_joint_rand_part) in prep_shares:
```suggestion
        for (verifiers_share, k_joint_rand_part) in prep_shares:
```

2023-10-10 19:44 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        leader_proof_share = []
```suggestion
        leader_proofs_share = []
```

2023-10-10 19:44 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        leader_proof_share = []
```suggestion
        leader_proofs_share = []
```

2023-10-10 19:44 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        binder = b'' if Prio3.PROOFS == 1 else byte(Prio3.PROOFS)
This imposes an upper bound on the value of `Prio3.PROOFS`. I think we should note this upper bound where `PROOFS` is first declared.

2023-10-10 19:44 UTC, cjpatton commented on poc/vdaf_prio3.py
> +            # Currently we encod this as one byte while deriving joing rands
```suggestion
            # We encode this as one byte while deriving joing rands
```

2023-10-10 19:44 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        # To be confirmed
If this comment is referring to a decision that still needs to be made, then I'd make it more clear.
```suggestion
        # TODO(issue#177) Decide how many proofs to use for each field type.
```

2023-10-10 19:44 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        elif field == Field96:
Do you plan to potentially use this field? Before you do, I think we should figure out if we can find a better prime modulus. We'd like to find something that's closer to a power of 2. (cc/ @divergentdave)

2023-10-10 19:44 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        return 0xFFFFFFFF
Since this is hard-coded for now, I think we should get rid of this function and declare this the same way we do for the other Prio3 variants: https://github.com/cfrg/draft-irtf-cfrg-vdaf/blob/main/poc/vdaf_prio3.py#L420

2023-10-10 19:44 UTC, cjpatton commented on poc/vdaf_prio3.py
> +def _test_prio3sumvec(num_proofs: Unsigned, field: FftField):
Same question as above: What convention are you following by prefixing this function with an underscore?

2023-10-10 19:44 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        return
It seems odd to silently skip the test if the number of proofs is not recommended. Also, should we test that it's greater than 0?

2023-10-10 19:44 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        binder = b'' if Prio3.PROOFS == 1 else byte(Prio3.PROOFS)
Reviewer note: I've confirmed the test vectors haven't changed.

2023-10-10 21:47 UTC, albertpl commented on poc/flp_generic.py
> +    for _field in [field.Field64, field.Field96, field.Field128]:
>Why prepend the underscore (_)?  Is this because field is already defined?

Yes.  Due to name collision. And we need to access `field.Field64` as well.
```
import field
```

2023-10-10 21:51 UTC, albertpl commented on poc/vdaf_prio3.py
> +        return
Do you mean that we should do negative tests? 

Like test with invalid configurations and expect it to throw exception? 
If so, I would like to introduce a dummy exception, like this
```
class MultiproofParamsNotRecommended(Exception):
    pass
```

This way we can throw & check this error. Let other `ValueError` to fail?

2023-10-10 21:52 UTC, albertpl commented on poc/vdaf_prio3.py
> +def _test_prio3sumvec(num_proofs: Unsigned, field: FftField):
I want to convey that this is an *internal* helper for `test_prio3sumvec`, not to used directly. What naming convention shall we follow?

2023-10-10 21:55 UTC, albertpl commented on poc/vdaf_prio3.py
> +        elif field == Field96:
No. So we will limit to `Field64` only then?

2023-10-10 21:57 UTC, albertpl commented on poc/vdaf_prio3.py
> +        leader_proof_share = []
I think this is reflected in the latest version.

2023-10-10 21:57 UTC, albertpl commented on poc/vdaf_prio3.py
> +        leader_proof_share = []
I think this is reflected in the latest version.

2023-10-10 21:57 UTC, albertpl commented on poc/vdaf_prio3.py
>          for (verifier_share, k_joint_rand_part) in prep_shares:
I think this is reflected in the latest version.

2023-10-10 21:58 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        elif field == Field96:
Yes. Better to not use `Field96` unless we have to :)

2023-10-10 22:00 UTC, cjpatton commented on poc/vdaf_prio3.py
> +def _test_prio3sumvec(num_proofs: Unsigned, field: FftField):
Sounds reasonable. I ask because I don't use Python a lot and I'm wondering about its conventions. I don't have an alternative in mind, so I'll just defer to you.

2023-10-10 22:01 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        return
I'm suggesting that tests to enforce the conditions they expect rather than skip testing if the conditions aren't meant. I would `assert` instead of `return`ing.

2023-10-10 22:02 UTC, cjpatton commented on poc/flp_generic.py
> +    for _field in [field.Field64, field.Field96, field.Field128]:
Let's maybe go with `f` here.

2023-10-10 22:02 UTC, albertpl commented on poc/vdaf_prio3.py
> +        verifier_share = []
Any chance you are not checking the [latest](i.e. 025c1c9) commit? Should be reflected, no?

2023-10-10 22:13 UTC, albertpl commented on poc/vdaf_prio3.py
> +        binder = b'' if Prio3.PROOFS == 1 else byte(Prio3.PROOFS)
Yes. We check this upper bound in `Prio3SumVecWithMultiproof.is_recommended`.  I add comments at first declaration as well.
Having said that, I am not sure what `PROOFS` we will put in the draft? I suppose it depends on robustness analysis. In any cases, due to computation cost, I would imagine > 255 proofs is prohibitive for most use cases.

2023-10-10 22:13 UTC, albertpl commented on poc/vdaf_prio3.py
> +        return
Got it. Since we agree to allow only one field size, this is much easier now. I will update.

2023-10-10 22:25 UTC, albertpl commented on poc/vdaf_prio3.py
> +    def joint_rands(Prio3, k_joint_rand_seed):
OK. Only `Field64` for now.

2023-10-10 22:32 UTC, albertpl commented on poc/vdaf_prio3.py
> +        return 0xFFFFFFFF
Will do. This does imply we have only one code point for this multiproof variant though

2023-10-13 17:11 UTC, cjpatton approved these changes
Looks good, just nit-picky comments left.

2023-10-13 17:11 UTC, cjpatton commented on poc/vdaf_prio3.py
> +    PROOFS = 1  # Number of proofs, default to 1, otherwise see `Prio3SumVecWithMultiproof.is_recommended`
```suggestion
    
    # Operational parameters
    PROOFS = 1  # Number of proofs, in range `[1, 256)`
```

2023-10-13 17:11 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        # Verify that all the proofs are well-formed and the input is valid.
```suggestion
        # Verify that each proof is well-formed and accepts the measurement.
```

2023-10-13 17:11 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        # Generate the proof(s) and shard it into proof(s) shares.
```suggestion
        # Generate the proofs and shard it into proof(s) shares.
```

2023-10-13 17:11 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        elif type(meas_share) == bytes and type(proofs_share) == bytes:  # helper
```suggestion
        elif type(meas_share) == bytes and type(proofs_share) == bytes:  # Helper
```

2023-10-13 17:11 UTC, cjpatton commented on poc/vdaf_prio3.py
> +            return 2 <= num_proofs < 0x100
```suggestion
            return 2 <= num_proofs < 256
```

2023-10-13 17:11 UTC, cjpatton commented on poc/vdaf_prio3.py
> +                       field: FftField) -> bool:
Avoid shadowing the imported `field` module
```suggestion
                       f: FftField) -> bool:
```

2023-10-13 17:11 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        return False
Future proofing
```suggestion
        elif field == Field128:
            return 1 <= num_proofs < 256
        return False
```

2023-10-13 17:11 UTC, cjpatton commented on poc/vdaf_prio3.py
> +        .with_params(10, 8, 9, num_proofs=num_proofs, field=field) \
```suggestion
        .with_params(10, 8, 9, num_proofs, field) \
```

2023-10-13 18:57 UTC, divergentdave approved these changes

2023-10-13 18:57 UTC, divergentdave commented on poc/vdaf_prio3.py
> +            # we encode it using one byteb in `joint_rands`
nit: typo
```suggestion
            # we encode it using one byte in `joint_rands`
```

2023-10-16 14:53 UTC, merged