Pass num_measurements when computing AggResult, add decode methods
cfrg/draft-irtf-cfrg-vdaf pull request #95
Opened 2022-06-29 23:01 UTC by divergentdave

This implements the change proposed by #92, passing `num_measurements` to `agg_shares_to_result()`. For Prio3, I decided to thread this through both the FLP and validity circuit layers, in new `decode()` methods. With this change, `encode()`, `truncate()`, and `decode()` now give us a more complete API for Prio's AFEs. To test this, I wrote a quick Average type that makes use of the new argument. I also took advantage of the new flexibility in `Prio3.AggResult` to change the output types of Prio3Aes128Count and Prio3Aes128Sum to be `Unsigned`, as it's more intuitive and ergonomic. (If we don't like that last bit, it's separated out in the commit history already)

2022-06-29 23:47 UTC, cjpatton reviewed
Thanks @divergentdave! I massively appreciate your thoroughness and attention to detail here. Adding test code to exercise the new logic is particularly appreciated.

I will give this a thorough review next Thursday, 7/7, when I'm back from PTO. In the meantime, a few high-level things:
* I'm a bit weary of the reference implementation defining the VDAF `Prio3Aes128Average` without also defining it in the draft itself. That said it's definitely useful to exercise the API changes that are introduced in this change. We should either add it it to the draft or rename it to something like `TestPrio3Aes128Average` (to suggest that it's there for testing, but may eventually go in the draft).
* Don't worry about updating the change log. We'll wait to do so until we're ready to cut the next draft.

2022-06-29 23:47 UTC, cjpatton commented on poc/vdaf_prio3.sage
> +        return new_cls
Does this actually need to be re-implemented?

2022-06-30 00:17 UTC, divergentdave commented on poc/vdaf_prio3.sage
> +        return new_cls
I re-implemented it to swap out `flp_generic.Sum` for `flp_generic.Average`. I could possibly define some new members on `Prio3Aes128Sum`, and and override a member for the validity circuit instead, but I figure the separate factory classmethod is less invasive.

2022-07-08 00:41 UTC, cjpatton requested changes
Excellent work! Just a few minor comments and this'll be ready to merge.

2022-07-08 00:41 UTC, cjpatton commented on poc/daf.sage
> +    def agg_shares_to_result(cls, _agg_param, agg_shares, num_measurements):
nit: Since this parameter gets ignored here, prefix it with `_`.

2022-07-08 00:41 UTC, cjpatton commented on poc/flp_generic.sage
> +        return [x.as_unsigned() for x in output]
A more descriptive name than `x` would be useful. How about `bucket_count`?

2022-07-08 00:41 UTC, cjpatton commented on poc/flp_generic.sage
> +    AggResult = float
I'm not sure we should have `float` as the result type, since the measurements are `Unsigned` and thus have a different precisison. What about defining this aggregation function as `floor(average(measurements))` and letting `AggResult = Unsigned`.

2022-07-08 14:31 UTC, cjpatton approved these changes

2022-07-08 17:01 UTC, merged